version: 2
jobs:
  build:
    docker:
      - image: ngfgrant/python-sonarqube:0.1

    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip3 install -r requirements.txt

      - run:
          name: Install Navigation
          command: |
            . venv/bin/activate
            pip3 install -e .

      - persist_to_workspace:
          root: /home/circleci
          paths:
            - project

  lint-and-unit-test:
    docker:
      - image: ngfgrant/python-sonarqube:0.1

    steps:
      - attach_workspace:
          at: /home/circleci

      - run:
          name: Linting
          command: |
            . venv/bin/activate
            make lint

      - run:
          name: Unit Test
          command: |
            . venv/bin/activate
            mkdir test-reports
            make test

      - run:
          name: Coverage
          command: |
            . venv/bin/activate
            make coverage

      - store_test_results:
          path: test-reports
          destination: test-reports

      - store_test_results:
          path: coverage.xml
          destination: coverage-reports

      - store_artifacts:
          path: test-reports
          destination: test-reports

      - store_artifacts:
          path: coverage.xml
          destination: coverage-reports

  sonar:
    docker:
      - image: ngfgrant/python-sonarqube:0.1

    steps:
      - attach_workspace:
          at: /home/circleci

      - run:
          name: Run Sonarqube
          command: |
            . venv/bin/activate
            make sonar

workflows:
  version: 2
  build-and-test:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/
      - lint-and-unit-test:
          requires:
            - build
          filters:
            tags:
              only: /.*/
      - sonar:
          requires:
            - build
            - lint-and-unit-test
